#!/bin/sh
while getopts ud option
do
  case "${option}"
  in
  u) UPX=true;;
  d) DEBUG=true;;
  esac
done
echo "Downloading..."
go get -d -v ./src/yggdrasil
for pkg in `go list ./cmd/...`; do
  binname="bin/$(basename "$file")"
  echo "Building: $pkg"
  go get -d -v "$pkg"
  #go build $@ $pkg
  if [ $DEBUG ]; then
    go build -tags debug -v "$pkg"
  else
    go build -ldflags="-s -w" -v "$pkg"
  fi
  if [ $UPX ]; then
    upx --brute "$binname"
  fi
done
